### ISSUE TITLE
Killed Karaf 4.1.1 after doing ALT-Backspace

### ISSUE THREAD

**Issue by grgrzybek** [jline/jline3#101]
I had command `config:property-set --pid org.ops4j.pax.url.mvn org.ops4j.pax.url.mvn.globalChecksumPolicy crash` and moved cursor left between `Checksum` and `Policy` and pressed backspace. I had:
````
2017-03-13T17:43:20,895 | ERROR | Karaf local console user karaf | ShellUtil                        | 43 - org.apache.karaf.shell.core - 4.1.1.SNAPSHOT | Exception caught while executing command
java.lang.StringIndexOutOfBoundsException: String index out of range: 162
	at java.lang.String.<init>(String.java:253) ~[?:?]
	at org.jline.reader.impl.BufferImpl.substring(BufferImpl.java:179) ~[50:org.jline:3.1.3]
	at org.jline.reader.impl.LineReaderImpl.backwardKillWord(LineReaderImpl.java:1352) ~[50:org.jline:3.1.3]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:533) [50:org.jline:3.1.3]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:337) [43:org.apache.karaf.shell.core:4.1.1.SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:?]
````

and my Karaf was stopped (correctly - like proper shutdown)

**Comment by gnodet** [comment]
Thx, I found a way to reproduce the problem:
```
        TestBuffer b = new TestBuffer("config:property-set --pid org.ops4j.pax.url.mvn org.ops4j.pax.url.mvn.globalChecksumPolicy crash")
                .op(BACKWARD_WORD)
                .op(BACKWARD_WORD)
                .append("odsa odsa ")
                .op(BACKWARD_WORD)
                .op(BACKWARD_KILL_WORD)
                .op(FORWARD_WORD)
                .op(FORWARD_WORD)
                .op(BACKWARD_KILL_WORD);
```
