### ISSUE TITLE
UnsatisfiedLinkError when using terminal-jansi on Linux

### ISSUE THREAD

**Issue by Minecrell** [jline/jline3#112]
This is probably related to https://github.com/jline/jline3/commit/33eb5d472b4f08945394490f46968b34e32694d2, it doesn't happen on JLine 3.2.0, only on the latest `3.3.0-SNAPSHOT`. I'm not sure if this is an issue in JLine or Jansi.

When I use the `jline-terminal-jansi` terminal implementation on Linux together with `LineReader`, I get a `java.lang.UnsatisfiedLinkError`:

```
java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.ioctl(IJLorg/fusesource/jansi/internal/CLibrary$WinSize;)I
        at org.fusesource.jansi.internal.CLibrary.ioctl(Native Method)
        at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:156)
        at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:59)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:474)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:383)
        at net.minecrell.test.ReaderTest.main(ReaderTest.java:21)
```

**Comment by gnodet** [comment]
Yeah, i was about to raise an issue about this one when I saw yours.
There's a problem with jansi 1.15 which does not include the needed native method, so I disabled the support on linux.

**Comment by rahil-c** [comment]
Hi gnodet, was wondering what is the mitigation or solution for this? Currently hitting this issue with spring starter shell 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jline.reader.LineReader]: Factory method 'lineReader' threw exception; nested exception is java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.ioctl(IJLorg/fusesource/jansi/internal/CLibrary$WinSize;)I
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 58 more
Caused by: java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.ioctl(IJLorg/fusesource/jansi/internal/CLibrary$WinSize;)I
	at org.fusesource.jansi.internal.CLibrary.ioctl(Native Method)
	at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:146)
	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:217)
	at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:755)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:308)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:127)
	at org.springframework.shell.boot.LineReaderAutoConfiguration.lineReader(LineReaderAutoConfiguration.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 59 more
```

**Comment by gnodet** [comment]
> Hi @gnodet , was wondering what is the mitigation or solution for this on linux? Currently hitting this issue with spring starter shell
> 
> spring shell version: 2.1.1 spring boot version: 2.7.3
> 
> I believe spring brings in jline https://mvnrepository.com/artifact/org.springframework.shell/spring-shell-core/2.1.1
> 
> ```
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jline.reader.LineReader]: Factory method 'lineReader' threw exception; nested exception is java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.ioctl(IJLorg/fusesource/jansi/internal/CLibrary$WinSize;)I
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
> 	... 58 more
> Caused by: java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.ioctl(IJLorg/fusesource/jansi/internal/CLibrary$WinSize;)I
> 	at org.fusesource.jansi.internal.CLibrary.ioctl(Native Method)
> 	at org.jline.terminal.impl.jansi.JansiNativePty.getSize(JansiNativePty.java:146)
> 	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
> 	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:217)
> 	at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:755)
> 	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:308)
> 	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:127)
> 	at org.springframework.shell.boot.LineReaderAutoConfiguration.lineReader(LineReaderAutoConfiguration.java:121)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
> 	... 59 more
> ```

Check the dependency tree of your project, you must be using an old version of JLine or Jansi.  This issue has been fixed 5 years ago and the spring dependency on JLine has been updated, so I think you must use another dependency (direct or transitive) on an old jline/jansi version.
