### ISSUE TITLE
Karaf crashes on windows when entering the word "bundle" on the shell

### ISSUE THREAD

**Issue by cschneider** [jline/jline3#116]
This issue opened in karaf seems to be an issue in jline:
https://issues.apache.org/jira/browse/KARAF-5078

Looks like the issue is in this method:
org.jline.terminal.impl.jna.win.WindowsAnsiOutputStream.write(WindowsAnsiOutputStream.java:189) 

---

Karaf shell behaves badly in Windows console. It appears better than 4.1.0 but still a problem. Command string start out red and turns dark blue while typing become virtually unreadable.

Most problematic though is that the shell crashed and brought down Karaf as a result of entering the word "bundle" at the console prompt. After the following tracebacks, the Felix shutdown sequence is displayed in the log.

2017-03-31T09:56:38,363 | ERROR | Karaf local console user karaf | ShellUtil                        | 42 - org.apache.karaf.shell.core - 4.1.1 | Exception caught while executing command
java.lang.NumberFormatException: For input string: "1B"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:?]
	at org.jline.terminal.impl.jna.win.WindowsAnsiOutputStream.write(WindowsAnsiOutputStream.java:189) ~[?:?]
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125) ~[?:?]
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458) ~[?:?]
	at org.apache.felix.gogo.runtime.Pipe$MultiChannel.write(Pipe.java:644) ~[42:org.apache.karaf.shell.core:4.1.1]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:?]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:?]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:?]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:?]
	at java.io.PrintStream.write(PrintStream.java:480) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:?]
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[?:?]
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104) ~[?:?]
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185) ~[?:?]
	at java.io.PrintStream.write(PrintStream.java:527) ~[?:?]
	at java.io.PrintStream.print(PrintStream.java:669) ~[?:?]
	at java.io.PrintStream.println(PrintStream.java:806) ~[?:?]
	at org.apache.felix.gogo.jline.Posix._main(Posix.java:134) ~[42:org.apache.karaf.shell.core:4.1.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:136) ~[42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.karaf.shell.impl.console.SessionFactoryImpl$ShellCommand.lambda$wrap$0(SessionFactoryImpl.java:195) ~[42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.karaf.shell.impl.console.SessionFactoryImpl$ShellCommand.execute(SessionFactoryImpl.java:241) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:560) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:486) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:375) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:417) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) [42:org.apache.karaf.shell.core:4.1.1]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) [42:org.apache.karaf.shell.core:4.1.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
2017-03-31T09:56:38,371 | ERROR | Karaf local console user karaf | ShellUtil                        | 42 - org.apache.karaf.shell.core - 4.1.1 | Exception caught while executing command
java.lang.NumberFormatException: For input string: "1Bl"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:580) [?:?]
	at java.lang.Integer.parseInt(Integer.java:615) [?:?]
	at org.jline.terminal.impl.jna.win.WindowsAnsiOutputStream.write(WindowsAnsiOutputStream.java:189) [49:org.jline:3.2.0]
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125) [?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) [?:?]
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) [?:?]
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295) [?:?]
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141) [?:?]
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) [?:?]
	at java.io.PrintWriter.flush(PrintWriter.java:320) [?:?]
	at org.jline.reader.impl.LineReaderImpl.flush(LineReaderImpl.java:640) [49:org.jline:3.2.0]
	at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2199) [49:org.jline:3.2.0]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:567) [49:org.jline:3.2.0]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:339) [42:org.apache.karaf.shell.core:4.1.1]
	at java.lang.Thread.run(Thread.java:745) [?:?]

**Comment by PascalSchumacher** [comment]
https://github.com/jline/jline3/commit/c0ce9c52a6691109c421a0ab82ce9c55b0ad6af1 removed WindowsAnsiOutputStream line 189 and a lot of surrounding lines, so maybe this issue is also fixed?

**Comment by gnodet** [comment]
I suspect that the fact the `AnsiOutputStream#write` method is not synchronized is causing the problem.
