### ISSUE TITLE
Errors detected with input reader

### ISSUE THREAD

**Issue by hyee** [jline/jline3#153]
The errors are not always happened, sometime during a long-running command, try to input some characters(`q` or `Ctrl+C` for example) may trigger the error. Below are 2 errors I found, platform is Windows：

```
 java.io.IOException: Write end dead
        at java.io.PipedInputStream.read(PipedInputStream.java:310)
        at java.io.PipedInputStream.read(PipedInputStream.java:377)
        at org.jline.utils.InputStreamReader.read(InputStreamReader.java:270)
        at org.jline.utils.InputStreamReader.read(InputStreamReader.java:200)
        at org.jline.utils.NonBlockingReader.run(NonBlockingReader.java:276)
        at java.lang.Thread.run(Thread.java:748)
 
 
 WARNING: Error in WindowsStreamPump
java.io.IOException: Read end dead
        at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:262)
        at java.io.PipedInputStream.receive(PipedInputStream.java:201)
        at java.io.PipedOutputStream.write(PipedOutputStream.java:122)
        at org.jline.terminal.impl.AbstractWindowsTerminal.processInputByte(AbstractWindowsTerminal.java:380)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:341)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Minecrell** [comment]
@gnodet I think this should no longer happen, or at least look different with my changes now, since the `PipedInputStream` is no longer used.

**Comment by gnodet** [comment]
Please reopen if you still see this issue with > 3.5.0
