### ISSUE TITLE
Cannot call Widget

### ISSUE THREAD

**Issue by MrCreeperkopf** [jline/jline3#183]
``
Exception in thread "main" java.lang.IllegalStateException
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:651)
        at de.dawnstudios.nnxcloud.main.Main.launch(Main.java:112)
        at de.dawnstudios.nnxcloud.main.Main.main(Main.java:40)
``
Main.java:112 is
``java
reader.callWidget(LineReader.CLEAR_SCREEN);
``
reader is of course a LineReader

**Comment by gnodet** [comment]
The `callWidget` method can only be called while the reader is inside a `readLine` call.
If that's not the case and you want to clear the screen, just use 
```
reader.getTerminal().puts(Capability.clear_screen);
reader.getTerminal().flush();
```
