### ISSUE TITLE
Exception in karaf 4.1.2 when resizing the screen while in log:tail on mac

### ISSUE THREAD

**Issue by cschneider** [jline/jline3#184]
- Start karaf 4.1.2
- log:tail
- Resize screen
- The exception below should appear

Exception in thread "SIGWINCH handler" java.lang.UnsupportedOperationException
	at org.jline.terminal.impl.NativeSignalHandler.handle(NativeSignalHandler.java:24)
	at org.apache.karaf.shell.impl.console.JLineTerminal.handle(JLineTerminal.java:280)
	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:65)
	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
	at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
	at com.sun.proxy.$Proxy54.handle(Unknown Source)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gnodet** [comment]
This is a Karaf specific problem and it has been fixed with https://github.com/apache/karaf/commit/cf66710143026a383849b985040600e5b5cafc8f.
