### ISSUE TITLE
Terminal.input() does not work on Windows

### ISSUE THREAD

**Issue by nicolas-dutertry** [jline/jline3#237]
When creating a new Terminal on Windows and reading bytes with Terminal.input(), the following exception is raised:
```
java.lang.ArrayIndexOutOfBoundsException: 4
        at org.jline.utils.NonBlocking$NonBlockingReaderInputStream.read(NonBlocking.java:116)
        at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:28)
```
I think there is a bug in class NonBlocking.NonBlockingReaderInputStream. The following code raise an exception:
```java
NonBlockingPumpReader reader = NonBlocking.nonBlockingPumpReader();
NonBlockingInputStream is = NonBlocking.nonBlockingStream(reader, Charset.forName("UTF-8"));
reader.getWriter().write("a");
int i = is.read(1000L);
```

**Comment by gnodet** [comment]
Thx for the unit test ! It's really very helpful.
