### ISSUE TITLE
TerminalBuilder.terminal() does not work in Intellij Console

### ISSUE THREAD

**Issue by holgerbrandl** [jline/jline3#263]
When running 
```
TerminalBuilder.terminal();
```
within Intellij IDEA, it fails with 
```
WARNING: Creating a dumb terminal
java.lang.IllegalStateException: Unable to create a system terminal
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:286)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:232)
	at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:72)
	at JavaTerminalTest.main(JavaTerminalTest.java:13)
	Suppressed: java.lang.NoClassDefFoundError: com/sun/jna/Platform
		at org.jline.terminal.impl.jna.JnaNativePty.current(JnaNativePty.java:40)
		at org.jline.terminal.impl.jna.JnaSupportImpl.current(JnaSupportImpl.java:16)
		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:330)
		... 3 more
	Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 6 more
	Suppressed: java.lang.UnsupportedOperationException
		at org.jline.terminal.impl.jansi.JansiSupportImpl.current(JansiSupportImpl.java:71)
		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:340)
		... 3 more
	Suppressed: java.io.IOException: Not a tty
		at org.jline.terminal.impl.ExecPty.current(ExecPty.java:44)
		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:349)
		... 3 more
	Caused by: java.io.IOException: Error executing 'tty': not a tty
		at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
		at org.jline.terminal.impl.ExecPty.current(ExecPty.java:41)
		... 4 more

```

![image](https://user-images.githubusercontent.com/200952/39549347-cfced8c0-4e5d-11e8-8899-6e28bf7cf2c4.png)

This relates to https://github.com/ctongfei/progressbar/issues/31

Since Intellij is a major IDE, it would be great if jline could support its console as well.

**Comment by gnodet** [comment]
See https://youtrack.jetbrains.com/issue/IDEA-132822

**Comment by gnodet** [comment]
And related to #261

**Comment by holgerbrandl** [comment]
A workaround seems to be to add
```
System.setProperty("org.jline.terminal.dumb", "true");
```
at the beginning of your application. This gets rid of the warning

**Comment by gnodet** [comment]
Closing this one as I don't think there's much JLine can do.
