### ISSUE TITLE
Problems resetting the pty on linux+jna

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#27]
```
Exception in thread "main" com.sun.jna.LastErrorException: [22] °§Ð
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:374)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy0.tcsetattr(Unknown Source)
	at org.jline.terminal.impl.jna.linux.LinuxNativePty.setAttr(LinuxNativePty.java:75)
	at org.jline.terminal.impl.AbstractPosixTerminal.close(AbstractPosixTerminal.java:64)
	at org.jline.terminal.impl.PosixSysTerminal.close(PosixSysTerminal.java:85)
	at org.apache.felix.gogo.jline.Main.main(Main.java:96)

```

**Comment by gnodet** [comment]
I suppose the problem comes from the fact that the `termios` structure used with JNA based pty does not directly come from a `tcgetattr` call.
I've tried with something like the following with no success:
```
    public void setAttr(Attributes attr) throws IOException {
        termios termios = new termios(attr);
        termios org = new termios();
        C_LIBRARY.tcgetattr(getSlave(), org);
        org.c_iflag = termios.c_iflag;
        org.c_oflag = termios.c_oflag;
        org.c_lflag = termios.c_lflag;
        org.c_cflag = termios.c_cflag;
        Log.warn("setattr: i: " + termios.c_iflag + ", o: " + termios.c_oflag + ", l: " + termios.c_lflag + ", c: " + termios.c_cflag);
        C_LIBRARY.tcsetattr(getSlave(), TCSADRAIN, org);
    }
```

**Comment by gnodet** [comment]
So the problems come from the cflag, and not using it seems to help.
