### ISSUE TITLE
Error "[1150] The specified program requires a newer version of Windows" in Cmder / ConEmu

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#276]
I've had a few reports of this error when using my JLine-powered console app in ConEMU or in Cmder (a portable terminal built on top of ConEmu).  The error is thrown from the `reader.readLine()` method and the stack trace usually looks similar to this:

```
com.sun.jna.LastErrorException: [1150] The specified program requires a newer version of Windows.
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:407)
        at com.sun.jna.Function.invoke(Function.java:353)
        at com.sun.jna.Library$Handler.invoke(Library.java:244)
        at org.jline.terminal.impl.jna.win.$Proxy0.SetConsoleMode(Unknown Source)
        at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.setConsoleMode(JnaWinSysTerminal.java:57)
        at org.jline.terminal.impl.AbstractWindowsTerminal.updateConsoleMode(AbstractWindowsTerminal.java:203)
        at org.jline.terminal.impl.AbstractWindowsTerminal.setAttributes(AbstractWindowsTerminal.java:189)
        at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:101)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:477)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:385)
```

I'm not sure if the issue is with Jline, Windows, JNA, or ConEmu / Cmder.  The message implies that Windows is out of date, but JLine certainly works fine inside of other terminals so I'm not sure if the JNA lib is detecting properly.  I've had ConEmu users report that updating to a newer version of ConEmu made this error go away.  I use ConEmu without issues on my Windows 7 SP1 but I downloaded the latest version of Cmder Lite today and confirmed that I get the error message. Cmder appears to be using an Alpha build of ConEmu though so it's hard to say what library is at fault here.

Let me know if you have any idea on troubleshooting this.  There is literally zero information about this error on the internet in conjunction with JNA, ConEmu, or Cmder, so if nothing else, maybe we'll be able figure out of some information that Google will index.

**Comment by gnodet** [comment]
Looking at google, that seems unrelated to JLine / ConEmu, etc...

**Comment by gnodet** [comment]
Have you tried the compatibility mode ? 
  https://www.visualstudio.com/fr/vs/support/vs2015/received-error-specified-program-requires-newer-version-windows/

**Comment by bdw429s** [comment]
Yes, I tried running Cmder in compatibility mode at the time and it made no difference. I'd love to know what the "specified program" is that the error message is referring to.

**Comment by gnodet** [comment]
Can I close this one ?

**Comment by bdw429s** [comment]
Well, we never really reached any consensus on exactly where the issue lies, but if you're sure that it's not a JLine bug I guess you can.  When my users run into this, I still have no answer for what they need to do to fix it.  I haven't had anyone report it in a while though.  Maybe it was a bad prerelease of Cmder?
