### ISSUE TITLE
jline-terminal-jansi + jline-reader + jansi were not worked

### ISSUE THREAD

**Issue by fuyutsuki** [jline/jline3#320]
### Environments:
* Win10 Home x86_64
```bash
> java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
* Execute on Windows PowerShell
* gradle
```gradle
plugins {
  id 'org.jetbrains.kotlin.jvm' version '1.3.0'
}

group 'jp.test.ansi'
version '1.0.0'

repositories {
  mavenCentral()
}

dependencies {
  compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
  compile "org.jline:jline-terminal-jansi:3.9.0"
  compile "org.jline:jline-reader:3.9.0"
  compile "org.fusesource.jansi:jansi:1.17.1"
}

compileKotlin {
  kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
  kotlinOptions.jvmTarget = "1.8"
}

jar {
  manifest {
    attributes "Main-Class": this.group + ".AnsiKt"
  }
  from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}
```

### Execute:
```bash
> java -jar ansi.jar
```

### Code:
```kotlin
val terminal: Terminal = TerminalBuilder.builder().system(true).dumb(false).build()
  val reader: LineReader = LineReaderBuilder.builder().build()
  val prompt = "prompt> "
  while (true) {
    var line: String? = null
    try {
      line = reader.readLine(prompt)
      println("$line was written!")
      if (line == "end") {
        println("end!")
        return
      }
    }catch (e: UserInterruptException) {
      // Ignore
    }catch (e: EndOfFileException) {
      return
    }
    if (line == null) continue
  }
```

### Error:
```bash
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:316)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:262)
        at jp.test.ansi.AnsiKt.test(Ansi.kt:40)
        at jp.test.ansi.AnsiKt.main(Ansi.kt:16)
        Suppressed: java.util.NoSuchElementException
                at java.base/java.util.ServiceLoader$2.next(Unknown Source)
                at java.base/java.util.ServiceLoader$2.next(Unknown Source)
                at java.base/java.util.ServiceLoader$3.next(Unknown Source)
                at org.jline.terminal.TerminalBuilder.load(TerminalBuilder.java:465)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:340)
                ... 3 more
        Suppressed: java.lang.UnsupportedOperationException
                at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:109)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:348)
                ... 3 more
```

**Comment by fuyutsuki** [comment]
It was not occurred on that used JNA.

**Comment by gnodet** [comment]
The exception in the code is supposed to be thrown when jansi version is less than 1.12, see https://github.com/jline/jline3/blob/master/terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/JansiSupportImpl.java#L102-L109.
The problem comes from the fact you're building your own jar so the code to recognize the package version (https://github.com/jline/jline3/blob/master/terminal-jansi/src/main/java/org/jline/terminal/impl/jansi/JansiSupportImpl.java#L34)  does not work anymore.  You need to include the required manifest entry to make the package version correct:

```
Name: org/fusesource/jansi/
Implementation-Version: 1.17.1
```

**Comment by fuyutsuki** [comment]
@gnodet Thank you, I'll try that!

**Comment by fuyutsuki** [comment]
Well, this worked! Thank you!
