### ISSUE TITLE
Enabling colors on dumb terminal cuases error

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#328]
I'm using the java property `org.jline.terminal.jna=false` to force a dumb terminal while doing some testing on Windows.  I tried to get colors back by adding `org.jline.terminal.dumb.color=true`.  While this succeeds in getting me 8 colors it generates an error in the console while JLine starts up.  The message is a "warning" level message, but I don't have any logging enabled for JLine.  

```
Nov 13, 2018 11:34:00 AM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type dumb-color
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
        at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:404)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:262)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:55)
        at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:852)
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:797)
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
        at system.util.readerfactory_cfc$cf.udfCall(/commandbox/system/util/ReaderFactory.cfc:84)
		... 
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 88 more
```

**Comment by gnodet** [comment]
There's a missing `dumb-color.caps` here: https://github.com/jline/jline3/tree/master/terminal/src/main/resources/org/jline/utils

It should contain something like the following (untested):
```
#      Reconstructed via infocmp from file: /usr/share/terminfo/64/dumb
dumb|80-column dumb tty with 256 colors,
        am,
        colors#256, cols#80, 
        bel=^G, cr=^M, cud1=^J, ind=^J,
```

**Comment by bdw429s** [comment]
@gnodet Thanks for the reply.  I can try sending this as a pull, but I'm not sure how to fully test it to see if it works.

**Comment by bjab** [comment]
Hi
I've provided pull-request with proper fix for dumb-color capabilities
