### ISSUE TITLE
NumberFormatException instead of IllegalArgumentException while loading jline2 history file from jline3

### ISSUE THREAD

**Issue by snuyanzin** [jline/jline3#332]
Here https://github.com/julianhyde/sqlline/issues/211 we faced with NumberFormatException (the trace is below) while loading old history instead of more human friendly 
```
Exception in thread "main" java.lang.IllegalArgumentException: Bad history file syntax! The history file `<User_home>\sqlline\history` may be an older history: please remove it or use a different history file.
```
Usually jline3 logic: find `:` and if it is not found then throw a human friendly exception otherwise parse timestamp from the left part from `:`. The code is here
https://github.com/jline/jline3/blob/5a781bba450404512ea8e32b073ae6f40e77bdb2/reader/src/main/java/org/jline/reader/impl/history/DefaultHistory.java#L100

But in that case the first row contains `:` while the left part is not a number so the jline3's logic fails here.

I guess the similar issue will be in case of large numbers as `java.time.Instant#create` 
> @throws DateTimeException if the instant exceeds the maximum or minimum instant

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "!connect jdbc"

	at sqlline.SqlLineArgsTest.checkScriptFile(SqlLineArgsTest.java:154)
	at sqlline.SqlLineArgsTest.testHelpAsQuestionMark(SqlLineArgsTest.java:490)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "!connect jdbc"
	at sqlline.SqlLineArgsTest.run(SqlLineArgsTest.java:93)
	at sqlline.SqlLineArgsTest.runScript(SqlLineArgsTest.java:119)
	at sqlline.SqlLineArgsTest.runScript(SqlLineArgsTest.java:98)
	at sqlline.SqlLineArgsTest.checkScriptFile(SqlLineArgsTest.java:145)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "!connect jdbc"
	at sqlline.SqlLineArgsTest.begin(SqlLineArgsTest.java:75)
	at sqlline.SqlLineArgsTest.run(SqlLineArgsTest.java:89)
	... 4 more
Caused by: java.lang.NumberFormatException: For input string: "!connect jdbc"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:578)
	at java.lang.Long.parseLong(Long.java:631)
	at org.jline.reader.impl.history.DefaultHistory.addHistoryLine(DefaultHistory.java:108)
	at org.jline.reader.impl.history.DefaultHistory.lambda$load$0(DefaultHistory.java:86)
	at org.jline.reader.impl.history.DefaultHistory.load(DefaultHistory.java:86)
	at org.jline.reader.impl.history.DefaultHistory.attach(DefaultHistory.java:69)
	at sqlline.SqlLine.getConsoleReader(SqlLine.java:614)
	at sqlline.SqlLine.begin(SqlLine.java:510)
	at sqlline.SqlLineArgsTest.begin(SqlLineArgsTest.java:72)
	... 5 more
```

**Comment by snuyanzin** [comment]
close as #333 merged
