### ISSUE TITLE
Key binding ctrl-\ is broken

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#441]
In nano pressing ctrl-\ ('search and replace') is causing demo application crash:

```
Exception in thread "main" java.io.IOError: java.io.IOException: Error executing 'stty -inlcr -icrnl min 0 time 1': stty: 'standard input': Input/output error
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
	at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:123)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:471)
	at org.apache.felix.gogo.jline.Shell.runShell(Shell.java:480)
	at org.apache.felix.gogo.jline.Shell.gosh(Shell.java:385)
	at org.apache.felix.gogo.jline.Main.main(Main.java:74)
	Suppressed: java.io.IOException: Error executing 'stty -inlcr ixon echo icanon iexten intr ^C quit ^\ susp ^Z lnext ^V discard ^O': stty: 'standard input': Input/output error
		at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
		at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:101)
		at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
		at org.jline.terminal.impl.AbstractPosixTerminal.close(AbstractPosixTerminal.java:76)
		at org.jline.terminal.impl.PosixSysTerminal.close(PosixSysTerminal.java:95)
		at org.apache.felix.gogo.jline.Main.main(Main.java:89)
Caused by: java.io.IOException: Error executing 'stty -inlcr -icrnl min 0 time 1': stty: 'standard input': Input/output error
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:101)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
```

**Comment by gnodet** [comment]
The `Ctrl+\` is usually used by the terminal to generate a `SIGQUIT` signal.
This is controlled by the [`VQUIT` control char](https://github.com/jline/jline3/blob/a24636dc5de83baa6b65049e8215fb372433b3b1/terminal/src/main/java/org/jline/terminal/Attributes.java#L30) of the terminal config.

In order to bind it, the terminal must be instructed to either not translate this key into the signal (this is controlled using the `LocalFlag.ISIG` flag), or to change the value of the `ControlChar.VQUIT`.

I'm not sure about the exception reported with the `exec` terminal though, I can't reproduce it in the nano app.

**Comment by gnodet** [comment]
@mattirn on my OSX platform, it prints a thread dump.  I'll check on my linux VM.

**Comment by gnodet** [comment]
Same on my linux VM when connecting through SSH.
@mattirn Can you report, the output of `stay -a` in your terminal ? Mine shows `quit = ^\` which explains why it sends a QUIT signal.

**Comment by gnodet** [comment]
On both my linux VM and OSX (M1), if I switch the key using `stty quit "^]"`, and launching the `gogo-repl` demo on `jna`, `jansi`, and `exec`, everything works correctly: hitting `^]` produces a thread dump and hitting `^\` does not do anything...

**Comment by gnodet** [comment]
Fwiw, https://pubs.opengroup.org/onlinepubs/009604499/basedefs/xbd_chap11.html#tag_11_01_04 mentions the error `EIO` (which seems to be 5 / `Input/output error` on linux) to be returned in case of an orphaned process.

**Comment by mattirn** [comment]
```
 % stty -a
speed 38400 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl ixon -ixoff
-iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```

**Comment by gnodet** [comment]
@mattirn should we close that one ?

**Comment by mattirn** [comment]
@gnodet, yes I think we can close this...
