### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: -1, Size: 1

### ISSUE THREAD

**Issue by ywy2090** [jline/jline3#450]
When reading a string that contains a special symbol eg: "!" IndexOutOfBoundsException maybe throw. 
for example    : 
a line like this  =>    
callByCNS HelloWorld:3 set "World!0x65cb0301278350abf61c6fda7e1a69a3f608970c12cea935bcf9ba106f3bd70678"

java.lang.IndexOutOfBoundsException: Index: -1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at org.jline.reader.impl.history.DefaultHistory.get(DefaultHistory.java:347)
	at org.jline.reader.impl.DefaultExpander.expandHistory(DefaultExpander.java:136)
	at org.jline.reader.impl.LineReaderImpl.acceptLine(LineReaderImpl.java:2837)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3626)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:604)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418)
	at console.ConsoleClient.main(ConsoleClient.java:95)

**Comment by mattirn** [comment]
You can disable event expansion to get rid of the problem. If you do not need event expansions you can take this as a final solution otherwise as work/around.
```
LineReader reader = LineReaderBuilder.builder()
                    .terminal(terminal)
                    .completer(completer)
                    .parser(parser)
                    .option(Option.DISABLE_EVENT_EXPANSION, true)
                    .build();
```
