### ISSUE TITLE
Jline 3.12 and up uses dumb terminal on Windows 7 cmd

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#454]
Attempting to upgrade CommandBox from JLine 3.10.0 to the latest and I hit an issue that seems to have started in 3.12.0.  The dumb terminal is used on Windows 7 and this error shows when I enable debug logging:

```
Oct 30, 2019 3:23:37 PM org.jline.utils.Log logr
FINE: Error creating JNA based terminal: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
        at org.jline.terminal.impl.jna.win.Kernel32.<clinit>(Kernel32.java:22)
        at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.<clinit>(JnaWinSysTerminal.java:29)
        at org.jline.terminal.impl.jna.JnaSupportImpl.winSysTerminal(JnaSupportImpl.java:39)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:337)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:55)
        at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:852)
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:797)
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
        at system.util.readerfactory_cfc$cf.udfCall(/commandbox/system/util/ReaderFactory.cfc:85)
        ...

Oct 30, 2019 3:23:37 PM org.jline.utils.Log logr
FINE: Error creating JANSI based terminal: null
java.lang.UnsupportedOperationException
        at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:135)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:345)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:55)
        at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:852)
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:797)
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1718)
        at system.util.readerfactory_cfc$cf.udfCall(/commandbox/system/util/ReaderFactory.cfc:85)
		...
		
Oct 30, 2019 3:23:37 PM org.jline.utils.Log logr
FINE: Using terminal DumbTerminal
```

The code in use is the same code that works on JLine 3.11.0

```js
var terminal = createObject( "java", "org.jline.terminal.TerminalBuilder" )
	.builder()
        .system( true )
        .nativeSignals( true )
        .signalHandler( jSignalHandler )
        .dumb( true )
	.build();
```

Tested on Java `1.8.0_161` and `11`.

**Comment by gnodet** [comment]
For Jansi, the problem is that the jansi version is not recognized as >= 1.12.  The version is retrieved from `org/fusesource/jansi/jansi.properties` file.

For JNA, you need to use version >= 5.3.1 (not sure which minimal version should be used, but that one works).

**Comment by bdw429s** [comment]
@gnodet Thanks for the reply, but I'm not sure what any of that means. I've never done anything directly with Jansi before, JLine has "just worked" out of the box.  JLine `3.11.0` works and on the same machine, JLine `3.12.0` doesn't work.  I assume this is a regression that needs addressed in JLine?

**Comment by mattirn** [comment]
@ bdw429s  Check your classpath! For JNA, you need to use version >= 5.3.1 and for Jansi >= 1.12.

**Comment by bdw429s** [comment]
I've done some digging and I think I may be putting the pieces together.  I've never added any jars to my classpath other than JLine to make Jline work which always led me to believe that JLine had everything it needed without any external dependencies (thus my confusion about what I was looking for on my classpath).  

I see now that Jansi and JNA are separate libraries and it just so happens that another jar I've always had in the classpath of this project already included the JNA classes bundled inside of itself which is apparently why JLine always worked.  It looks like I've always had JNA 4.3.0 in my classpath so I'll see if I can get away with bumping that without breaking the other libraries that depend on it.

**Comment by bdw429s** [comment]
I looks like adding the Jansi jar works as well.  Is there a preference to whether I should be using JNA or Jansi with JLine?

**Comment by gnodet** [comment]
Not really, on windows, both should provide jline with the required features and both use JNI.  JNA is a bigger library though.

**Comment by bdw429s** [comment]
The decision to start bundling Jasni may be made for me right now.  I'm also using this library which is still stuck on JNA 4.x
https://github.com/dorkbox/SystemTray/issues/103
