### ISSUE TITLE
Display NPE

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#490]
Got NPE when using tab-completion:
```
 java.lang.NullPointerException: null
        at org.jline.utils.Display.wcwidth(Display.java:491) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.toColumns(LineReaderImpl.java:5173) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.computePost(LineReaderImpl.java:5152) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.computePost(LineReaderImpl.java:5105) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:4990) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:4977) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4591) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4362) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4301) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3796) ~[jline-3.13.3-SNAPSHOT.jar:?]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665) ~[jline-3.13.3-SNAPSHOT.jar:?]
```

Method `wcwidth()` could be robusted as
```
    public int wcwidth(String str) {
        return str != null ? AttributedString.fromAnsi(str).columnLength() : 0;
    }
```

**Comment by gnodet** [comment]
Agreed, but I would also change the `Candidate` constructor to avoid the problem:
```
    public Candidate(String value, String displ, String group, String descr, String suffix, String key, boolean complete) {
        this.value = Objects.requireNonNull(value);
        this.displ = Objects.requireNonNull(displ);
       ...
    }
```
