### ISSUE TITLE
BufferUnderflowException and IllegalArgumentException in NonBlockingPumpReader

### ISSUE THREAD

**Issue by hyee** [jline/jline3#493]
The issue happens when manually write `LineReaderImpl.BRACKETED_PASTE_BEGIN` into the reader before reading the input string.

When `readBuffer.remaining()<64` then:
```
java.nio.BufferUnderflowException
        at java.nio.HeapCharBuffer.get(HeapCharBuffer.java:151)
        at java.nio.CharBuffer.get(CharBuffer.java:715)
        at org.jline.utils.NonBlockingPumpReader.readBuffered(NonBlockingPumpReader.java:118)
        at org.jline.keymap.BindingReader.readStringUntil(BindingReader.java:134)
        at org.jline.reader.impl.LineReaderImpl.doReadStringUntil(LineReaderImpl.java:921)
        at org.jline.reader.impl.LineReaderImpl.beginPaste(LineReaderImpl.java:5647)
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3796)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:493)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:479)
```

After fix the above exception, another is thrown:
```
java.lang.IllegalArgumentException: timeout value is negative
        at java.lang.Object.wait(Native Method)
        at org.jline.utils.NonBlockingPumpReader.wait(NonBlockingPumpReader.java:56)
        at org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:102)
        at org.jline.utils.NonBlockingPumpReader.readBuffered(NonBlockingPumpReader.java:128)
        at org.jline.keymap.BindingReader.readStringUntil(BindingReader.java:134)
        at org.jline.reader.impl.LineReaderImpl.doReadStringUntil(LineReaderImpl.java:921)
        at org.jline.reader.impl.LineReaderImpl.beginPaste(LineReaderImpl.java:5647)
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3796)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:493)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:479)
```

**Comment by hyee** [comment]
Besides, `readBuffer` and `writeBuffer` could infinitely block each other on the `wait` function when inputting `BRACKETED_PASTE_BEGIN`+huge string (1MB)
