### ISSUE TITLE
need support securtCRT terminal types -  Linux

### ISSUE THREAD

**Issue by ft20082** [jline/jline3#496]
Options -> category -> Terminal -> Emulation : 
Linux - not support now 
change to others is OK

it report error :

[root@dn1 phoenix-5.1.0-cdh6.1.1-SNAPSHOT]# ./bin/sqlline.py 
Exception in thread "main" java.io.IOError: java.lang.UnsupportedOperationException
        at org.jline.utils.Curses.tputs(Curses.java:62)
        at org.jline.utils.Curses.tputs(Curses.java:45)
        at org.jline.keymap.KeyMap.key(KeyMap.java:243)
        at org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:5666)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:5674)
        at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5387)
        at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5363)
        at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:266)
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
        at sqlline.SqlLine.getConsoleReader(SqlLine.java:626)
        at sqlline.SqlLine.begin(SqlLine.java:527)
        at sqlline.SqlLine.start(SqlLine.java:270)
        at sqlline.SqlLine.main(SqlLine.java:201)
Caused by: java.lang.UnsupportedOperationException
        at org.jline.utils.Curses.doTputs(Curses.java:78)
        at org.jline.utils.Curses.tputs(Curses.java:60)
        ... 21 more
[root@dn1 phoenix-5.1.0-cdh6.1.1-SNAPSHOT]#

**Comment by gnodet** [comment]
There must be an unsupported sequence in the JLine tput code.
Could you run `infocmp` and report the output please ?

**Comment by ft20082** [comment]
> There must be an unsupported sequence in the JLine tput code.
> Could you run `infocmp` and report the output please ?

[root@dn1 ~]# infocmp
#       Reconstructed via infocmp from file: /usr/share/terminfo/l/linux
linux|linux console,
        am, bce, ccc, eo, mir, msgr, xenl, xon,
        colors#8, it#8, ncv#18, pairs#64,
        acsc=+\020\,\021-\030.^Y0\333`\004a\261f\370g\361h\260i\316j\331k\277l\332m\300n\305o~p\304q\304r\304s_t\303u\264v\301w\302x\263y\363z\362{\343|\330}\234~\376,
        bel=^G, blink=\E[5m, bold=\E[1m, civis=\E[?25l\E[?1c,
        clear=\E[H\E[J, cnorm=\E[?25h\E[?0c, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?25h\E[?8c, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h\E[?5l$<200/>, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@, ich1=\E[@,
        il=\E[%p1%dL, il1=\E[L, ind=^J,
        initc=\E]P%p1%x%p2%{255}%*%{1000}%/%02x%p3%{255}%*%{1000}%/%02x%p4%{255}%*%{1000}%/%02x,
        kb2=\E[G, kbs=\177, kcbt=\E[Z, kcub1=\E[D, kcud1=\E[B,
        kcuf1=\E[C, kcuu1=\E[A, kdch1=\E[3~, kend=\E[4~, kf1=\E[[A,
        kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[25~,
        kf14=\E[26~, kf15=\E[28~, kf16=\E[29~, kf17=\E[31~,
        kf18=\E[32~, kf19=\E[33~, kf2=\E[[B, kf20=\E[34~,
        kf3=\E[[C, kf4=\E[[D, kf5=\E[[E, kf6=\E[17~, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
        kmous=\E[M, knp=\E[6~, kpp=\E[5~, kspd=^Z, nel=^M^J, oc=\E]R,
        op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=\E[10m,
        rmam=\E[?7l, rmir=\E[4l, rmpch=\E[10m, rmso=\E[27m,
        rmul=\E[24m, rs1=\Ec\E]R, sc=\E7, setab=\E[4%p1%dm,
        setaf=\E[3%p1%dm,
        sgr=\E[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;%?%p9%t;11%;m,
        sgr0=\E[0;10m, smacs=\E[11m, smam=\E[?7h, smir=\E[4h,
        smpch=\E[11m, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?6c, u9=\E[c,
        vpa=\E[%i%p1%dd,

**Comment by gnodet** [comment]
This has been fixed in #408 with https://github.com/jline/jline3/commit/864f2063255b6f1bedce1605ae4ff76d5f22b55c#diff-2768cc9b5404a72434cf8057d2175eb4
The sqlline needs to be upgraded to a more recent version of jline.
