### ISSUE TITLE
handle java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by stbischof** [jline/jline3#526]
I could not reproduce it. but i got this:

JLine: do you wish to see all 8 possibilities (0 lines)?gogoArithmeticException: / by zero
java.lang.ArithmeticException: / by zero
	at org.jline.utils.Display.update(Display.java:302)
	at org.jline.utils.Display.update(Display.java:99)
	at org.jline.reader.impl.LineReaderImpl.lambda$doList$38(LineReaderImpl.java:5035)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4046)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3866)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3802)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5044)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:4971)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4585)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4362)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4301)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3796)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:493)
	at org.apache.felix.gogo.jline.Shell.runShell(Shell.java:489)
	at org.apache.felix.gogo.jline.Shell.gosh(Shell.java:394)
	at org.apache.felix.gogo.jline.Activator.lambda$0(Activator.java:138)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mattirn** [comment]
I'm afraid we cannot do much if we are not able to reproduce the problem.
Anyway what is the version of JLine you have seen this?

**Comment by mattirn** [comment]
Could it be that JLine fails because of eclipse console environment? 
I have never tried to run JLine directly from IDE.

**Comment by stbischof** [comment]
I am sure that it is because of eclipse. But i think every result of calculation is better then this error.

**Comment by mattirn** [comment]
JLine needs a real terminal to work. If you're not launching the JVM from a terminal, JLine will fail to grab the terminal and it will create dumb terminal with no advanced features.
