### ISSUE TITLE
Null Pointer Exception with `infocmp` warning

### ISSUE THREAD

**Issue by konteal** [jline/jline3#550]
The terminal I use is `rxvt-unicode-256color` and starting the Scala interpreter in it immediately gives a null pointer exception, see https://pastebin.com/WMbSRTgk. The readline I get then fails to interpret control keys such as `Home`, `End`, `Delete` and `Backspace`, giving back control sequences like `[~7` and so.

However, running `infocmp -C rxvt-unicode-256color` works just fine in my terminal. I asked on a Scala chatroom about this and have been told that this may be a JLine bug, so I’m reporting this here in case he’s right.

So far, exporting another terminal, as in`export TERM=xterm-256color` will mitigate the problem: The null pointer exception disappears and the readline I get only fails with `Home` and `End`, other control keys work fine.

**Comment by SethTisue** [comment]
previously in this area: https://github.com/jline/jline3/issues/533

**Comment by gnodet** [comment]
Have you repackaged JLine ? This is caused by a missing resource, which should not happen if you're using the jline jars.

**Comment by mattirn** [comment]
Thanks @gnodet, after renaming rxvt files:

```
 % ./build demo
Launching Gogo JLine...
Classpath: /home/matti/git/jline3b/demo/target/classes:/home/matti/git/jline3b/demo/target/lib/jline-groovy-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-terminal-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-builtins-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-style-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-reader-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/jline-console-3.15.1-SNAPSHOT.jar:/home/matti/git/jline3b/demo/target/lib/org.apache.felix.gogo.runtime-1.1.2.jar:/home/matti/git/jline3b/demo/target/lib/org.apache.felix.gogo.jline-1.1.4.jar
Exception in thread "main" java.io.IOError: java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at org.jline.utils.Curses.tputs(Curses.java:62)
	at org.jline.utils.Curses.tputs(Curses.java:45)
	at org.jline.keymap.KeyMap.key(KeyMap.java:243)
	at org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:6093)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:6101)
	at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5811)
	at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5787)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:293)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
	at org.apache.felix.gogo.jline.Shell.gosh(Shell.java:359)
	at org.apache.felix.gogo.jline.Main.main(Main.java:74)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.jline.utils.Curses.doTputs(Curses.java:359)
	at org.jline.utils.Curses.tputs(Curses.java:60)
	... 19 more
```

Removing `rxvt-basic.caps` file all the records that finish to $ i.e. `kDC=\E[3$, kEND=\E[8$, kHOM=\E[7$, ...` the above exception disappear. I do not know if this can be taken as a solution to the problem?

**Comment by gnodet** [comment]
> 
> If we change the line
> 
> https://github.com/jline/jline3/blob/d2ac4ef422409bbd4b37a41d10e6b66fb54bb926/terminal/src/main/java/org/jline/utils/Curses.java#L359
> 
> 
> with
> ```
>                     if (index < length && str.charAt(index) == '<') {
> ```
> 
> then we do not need to edit caps file.

It looks like a good solution to me.
