### ISSUE TITLE
Typing "?" or "+" (without even hitting 'Enter') produces this exception (Win10/Linux/Ubuntu)

### ISSUE THREAD

**Issue by nivanov** [jline/jline3#584]
▶ ?
java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0
?.*
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1094)
        at org.jline.reader.impl.LineReaderImpl.matchPreviousCommand(LineReaderImpl.java:3971)
        at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4005)
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3863)
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3799)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:694)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
        ...

**Comment by mattirn** [comment]
Thanks, char '+' was still missing from list of the chars to be escaped.  #570
