### ISSUE TITLE
Can't use system terminal on windows even using JNA/Jansi library

### ISSUE THREAD

**Issue by crafter1415** [jline/jline3#591]
I put all the following libraries but still fail to create a system terminal
> jna-5.6.0
> jansi-1.18
> jline-terminal-jna-3.16.0
> jline-terminal-jansi-3.16.0
> jline-3.16.1

I tried disabling the dumb terminal, but in that case, I got the following error message
```
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:322)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:265)
	at main.Main.main(Main.java:13)
	Suppressed: com.sun.jna.LastErrorException: [6] ハンドルが無効です。 * Invalid handle
		at com.sun.jna.Native.invokeVoid(Native Method)
		at com.sun.jna.Function.invoke(Function.java:415)
		at com.sun.jna.Function.invoke(Function.java:361)
		at com.sun.jna.Library$Handler.invoke(Library.java:265)
		at org.jline.terminal.impl.jna.win.$Proxy0.GetConsoleMode(Unknown Source)
		at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.createTerminal(JnaWinSysTerminal.java:40)
		at org.jline.terminal.impl.jna.JnaSupportImpl.winSysTerminal(JnaSupportImpl.java:39)
		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:331)
		... 2 more
	Suppressed: java.io.IOException: Failed to get console mode: S0n0�d\O�0ckW0O0B}�NW0~0W0_00
		at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.createTerminal(JansiWinSysTerminal.java:47)
		at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:129)
		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:341)
		... 2 more

```

How can I solve this problem?

**Comment by mattirn** [comment]
@crafter1415 which Windows version and terminal (cmd, PowerShell, ...) are you using?

**Comment by crafter1415** [comment]
> @crafter1415 which Windows version and terminal (cmd, PowerShell, ...) are you using?

Microsoft Windows [Version 10.0.19041.572]

It worked on cmd.exe (It was my lack of confirmation),
But I also want to know how to run it on the eclipse terminal if possible.

**Comment by mattirn** [comment]
As far as I know on Eclipse console you can create only dumb terminal.
JLine needs a real terminal to work. If you're not launching the JVM from a terminal, JLine will fail to grab the terminal and it will create dumb terminal.
