### ISSUE TITLE
Windows 10 cmd/PowerShell JLine blocks when using with Jansi 2.0 

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#594]
Launching demo app with Jansi blocks after writing 1-2 chars and `WindowsStreamPump` consumes available CPU.

```
C:\>jstack 16284
2020-10-27 17:59:24
Full thread dump OpenJDK 64-Bit Server VM (11+28 mixed mode):

Threads class SMR info:
_java_thread_list=0x0000028958c663a0, length=11, elements={
0x0000028934895000, 0x0000028957814800, 0x00000289580ab800, 0x00000289580f8800,
0x00000289580f9000, 0x00000289580fd000, 0x0000028958101800, 0x0000028958104000,
0x000002895825c800, 0x0000028958266000, 0x00000289587e8000
}

"main" #1 prio=5 os_prio=0 cpu=640.63ms elapsed=467.69s tid=0x0000028934895000 nid=0x11c0 waiting on condition  [0x000000c1b42fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11/Native Method)
        - parking to wait for  <0x00000007109243f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11/LockSupport.java:234)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11/AbstractQueuedSynchronizer.java:2211)
        at org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:78)
        at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
        at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
        at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
        at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
        at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:914)
        at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:947)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:642)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:498)
        at org.apache.felix.gogo.jline.Shell.runShell(Shell.java:480)
        at org.apache.felix.gogo.jline.Shell.gosh(Shell.java:385)
        at org.apache.felix.gogo.jline.Main.main(Main.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=2 cpu=0.00ms elapsed=467.65s tid=0x0000028957814800 nid=0x2128 waiting on condition  [0x000000c1b49ff000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=467.65s tid=0x00000289580ab800 nid=0x229c in Object.wait()  [0x000000c1b4aff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11/Native Method)
        - waiting on <0x0000000710906180> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000710906180> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=467.63s tid=0x00000289580f8800 nid=0x758 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 cpu=0.00ms elapsed=467.63s tid=0x00000289580f9000 nid=0x28a0 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 cpu=531.25ms elapsed=467.63s tid=0x00000289580fd000 nid=0x3f7c waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=2 cpu=578.13ms elapsed=467.63s tid=0x0000028958101800 nid=0x4184 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=467.63s tid=0x0000028958104000 nid=0x1c3c runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #10 daemon prio=9 os_prio=0 cpu=0.00ms elapsed=467.59s tid=0x000002895825c800 nid=0x2eb8 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=467.58s tid=0x0000028958266000 nid=0x20b8 in Object.wait()  [0x000000c1b52fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11/Native Method)
        - waiting on <no object reference available>
        at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000710904d00> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11/Thread.java:834)
        at jdk.internal.misc.InnocuousThread.run(java.base@11/InnocuousThread.java:134)

"WindowsStreamPump" #14 daemon prio=5 os_prio=0 cpu=462828.13ms elapsed=467.17s tid=0x00000289587e8000 nid=0xc8c runnable  [0x000000c1b54ff000]
   java.lang.Thread.State: RUNNABLE
        at org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:125)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$34/0x00000008000ea840.run(Unknown Source)
        at java.lang.Thread.run(java.base@11/Thread.java:834)

"VM Thread" os_prio=2 cpu=0.00ms elapsed=467.66s tid=0x0000028957813800 nid=0x16e4 runnable

"GC Thread#0" os_prio=2 cpu=31.25ms elapsed=467.68s tid=0x00000289348ac800 nid=0x2d5c runnable

"GC Thread#1" os_prio=2 cpu=31.25ms elapsed=466.97s tid=0x00000289587e1000 nid=0x31a4 runnable

"GC Thread#2" os_prio=2 cpu=15.63ms elapsed=466.97s tid=0x00000289587fb800 nid=0x3a60 runnable

"GC Thread#3" os_prio=2 cpu=15.63ms elapsed=466.97s tid=0x0000028958ab9800 nid=0x2684 runnable

"G1 Main Marker" os_prio=2 cpu=0.00ms elapsed=467.68s tid=0x000002893490c800 nid=0x418c runnable

"G1 Conc#0" os_prio=2 cpu=0.00ms elapsed=467.68s tid=0x000002893490e800 nid=0x3d60 runnable

"G1 Refine#0" os_prio=2 cpu=0.00ms elapsed=467.68s tid=0x00000289576cf800 nid=0x3738 runnable

"G1 Young RemSet Sampling" os_prio=2 cpu=0.00ms elapsed=467.68s tid=0x00000289576d2800 nid=0x347c runnable
"VM Periodic Task Thread" os_prio=2 cpu=0.00ms elapsed=467.59s tid=0x0000028958265800 nid=0xadc waiting on condition

JNI global refs: 17, weak refs: 0
```

**Comment by derklaro** [comment]
GitBash in combination with windows 10 2004 blocks too
