### ISSUE TITLE
Problem with JnaNativePty

### ISSUE THREAD

**Issue by Nnidyu** [jline/jline3#6]
Hi,

I have noticed that the default terminal returned by `TerminalBuilder.terminal()` is not working.
The default configuration created by the builder on my system (Fedora 24) is equivalent to manually creating:
`new PosixSysTerminal("jline", "xterm-256color", JnaNativePty.current(), "UTF-8", true);`

And it gives the following error when calling `LineReader.readLine()` leaving the terminal unusable:
```
Exception in thread "main" com.sun.jna.LastErrorException: [22]
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:374)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy21.tcsetattr(Unknown Source)
	at org.jline.terminal.impl.jna.linux.LinuxNativePty.setAttr(LinuxNativePty.java:71)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:36)
	at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:94)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:444)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
	at pl.edu.agh.age.console.Console.mainLoop(Console.java:104)
	at pl.edu.agh.age.console.ConsoleBootstrapper.main(ConsoleBootstrapper.java:67)
```

However, the version with ExecPty works without problems:
`new PosixSysTerminal("jline", "xterm-256color", ExecPty.current(), "UTF-8", true);`

I don't think this is expected.

**Comment by gnodet** [comment]
I've been able to reproduce it using
```
java -classpath target/classes:target/test-classes:/home/gnodet/.m2/repository/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar org.jline.example.Example color
```

**Comment by gnodet** [comment]
This should be fixed, please reopen if needed.
