### ISSUE TITLE
FileNameCompleter fails in highlight: NoSuchMethodError

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#622]
@gnodet I'm almost :) sure this worked yesterday. Highlight fails when highlighting files based on file type.

```
groovy-repl> data=slurp de
java.lang.NoSuchMethodError: org.jline.utils.AttributedStyle.getStyle()J
	at org.jline.builtins.Completers$FileNameCompleter.getDisplay(Completers.java:410)
	at org.jline.builtins.Completers$FileNameCompleter.lambda$complete$0(Completers.java:367)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jline.builtins.Completers$FileNameCompleter.complete(Completers.java:359)
	at org.jline.reader.impl.completer.AggregateCompleter.lambda$complete$0(AggregateCompleter.java:73)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.jline.reader.impl.completer.AggregateCompleter.complete(AggregateCompleter.java:73)
	at org.jline.builtins.Completers$OptionCompleter.complete(Completers.java:883)
	at org.jline.reader.impl.completer.ArgumentCompleter.complete(ArgumentCompleter.java:141)
	at org.jline.reader.impl.completer.SystemCompleter.complete(SystemCompleter.java:55)
	at org.jline.reader.impl.completer.AggregateCompleter.lambda$complete$0(AggregateCompleter.java:73)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.jline.reader.impl.completer.AggregateCompleter.complete(AggregateCompleter.java:73)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4404)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4370)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4309)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3801)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:670)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:459)
	at org.jline.demo.Repl.main(Repl.java:333)
```

**Comment by mattirn** [comment]
Reason was simply bad compilation. I compiled before native-image and I think demo was mixin jars. I recompiled jline and that fixed a problem.
