### ISSUE TITLE
picocli-shell with jline3 throws StackOverflowError

### ISSUE THREAD

**Issue by vicasong** [jline/jline3#640]
I completely copied the example code to run the demo program, but the program throws an exception when I enter any command.

[example code](https://github.com/remkop/picocli/tree/master/picocli-shell-jline3#jline-316-and-picocli-44-example)
[relevant issue](https://github.com/remkop/picocli/issues/1310)

- Error

```text
Invalid command: ?
java.lang.StackOverflowError
	at org.jline.utils.AttributedCharSequence.columnSplitLength(AttributedCharSequence.java:332)
	at org.jline.utils.AttributedCharSequence.columnSplitLength(AttributedCharSequence.java:324)
	at org.jline.reader.impl.LineReaderImpl.insertSecondaryPrompts(LineReaderImpl.java:4179)
	at org.jline.reader.impl.LineReaderImpl.insertSecondaryPrompts(LineReaderImpl.java:4174)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4003)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3868)
	at org.jline.reader.impl.LineReaderImpl.doList(LineReaderImpl.java:5020)
	at org.jline.reader.impl.LineReaderImpl.clearChoices(LineReaderImpl.java:4993)
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:4020)
<... etc....>
```

**Comment by mattirn** [comment]
You probably should add Jansi or JNA lib in your class path. See JLine [README](https://github.com/jline/jline3):

"On the Windows platform, relying on native calls is mandatory, so you need to have either Jansi or JNA library in your classpath along with the jline-terminal-jansi or jline-terminal-jna jar. Failing to do so will create a dumb terminal with no advanced capabilities."

Stackoverflow when using dumb terminal has been fixed in commit https://github.com/jline/jline3/commit/bb5e85afd9009e9d3d917a19dcb0deab4b9b0922. You should use JLine version 3.18.0 or greater.

**Comment by vicasong** [comment]
Thank you very much. The problem was solved after I upgraded the jline version.
