### ISSUE TITLE
UniversalDetector seems to have problems with Quarkus/Graalvm native images

### ISSUE THREAD

**Issue by ar** [jline/jline3#786]
This exception apparently prevents JLine from running as a Quarkus native image (quite useful for CLI commands).

Wonder if there's a work around for this problem.

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.mozilla.universalchardet.UniversalDetector. This error is reported at image build time because class org.jline.builtins.Nano$Buffer is registered for linking at image build time by command line
Detailed message:
Trace: 
	at parsing org.jline.builtins.Nano$Buffer.read(Nano.java:254)
Call path from entry point to org.jline.builtins.Nano$Buffer.read(InputStream): 
	at org.jline.builtins.Nano$Buffer.read(Nano.java:245)
	at org.jline.builtins.Nano$Buffer.open(Nano.java:225)
	at org.jline.builtins.Nano.run(Nano.java:2177)
	at org.jline.reader.impl.LineReaderImpl.editAndAddInBuffer(LineReaderImpl.java:1089)
	at org.jline.reader.impl.LineReaderImpl.editAndExecute(LineReaderImpl.java:3601)
	at org.jline.reader.impl.LineReaderImpl$$Lambda$1101/0x00000007c19d9c60.apply(Unknown Source)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)

```

**Comment by mattirn** [comment]
JLine graal demo is compiled using option `--allow-incomplete-classpath `:

https://github.com/jline/jline3/blob/8b89ff5f305e9865214f6ff3b5545723a311fcd3/graal/pom.xml#L121

I think that it would resolve your problem.
