### ISSUE TITLE
JLine 3.24.0 crashes 

### ISSUE THREAD

**Issue by wendigo** [jline/jline3#889]
JLine 3.21.0 was working, while Jline 3.24.0 crashes with following exception for `trino-cli` (https://github.com/trinodb/trino/tree/master/client/trino-cli):

```
master$ client/trino-cli/target/trino-cli-431-SNAPSHOT-executable.jar
trino> s;
Exception in thread "main" java.io.IOError: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:57)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:774)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:553)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:538)
	at io.trino.cli.InputReader.readLine(InputReader.java:71)
	at io.trino.cli.Console.runConsole(Console.java:244)
	at io.trino.cli.Console.run(Console.java:192)
	at io.trino.cli.Console.call(Console.java:109)
	at io.trino.cli.Console.call(Console.java:79)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.trino.cli.Trino.main(Trino.java:47)
Caused by: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:48)
	at org.jline.terminal.impl.exec.ExecPty.doSetAttr(ExecPty.java:104)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:46)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:55)
	... 17 more
```

**Comment by wendigo** [comment]
It can be reproduces with homebrew installed coreutils on MacOS:

```
❯ PATH=/opt/homebrew/opt/coreutils/libexec/gnubin/:$PATH ./client/trino-cli/target/trino-cli-431-SNAPSHOT-executable.jar
trino> s;
Exception in thread "main" java.io.IOError: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:57)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:774)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:553)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:538)
        at io.trino.cli.InputReader.readLine(InputReader.java:71)
        at io.trino.cli.Console.runConsole(Console.java:244)
        at io.trino.cli.Console.run(Console.java:192)
        at io.trino.cli.Console.call(Console.java:109)
        at io.trino.cli.Console.call(Console.java:79)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.trino.cli.Trino.main(Trino.java:47)
Caused by: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
        at org.jline.utils.ExecHelper.exec(ExecHelper.java:48)
        at org.jline.terminal.impl.exec.ExecPty.doSetAttr(ExecPty.java:104)
        at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:46)
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:55)
        ... 17 more
(base)
```

It works with the MacOS provided stty (tested on Sonoma)

**Comment by wendigo** [comment]
I don't know whether https://github.com/jline/jline3/commit/12219fa5a5fd56dbe0731519032c862fc4e39388 was removed intentionally, but applying this change to master fixes this issue.

**Comment by wendigo** [comment]
@gnodet works!
