### ISSUE TITLE
Compilation of GraalVM native image fails when adding jline as dependency

### ISSUE THREAD

**Issue by en-milie** [jline/jline3#936]
I have an app that uses the terminal API and my build started to fail with the latest version 3.25.1 with the below stack trace:

```
Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.UserError$UserException: Class initialization of org.jline.nativ.Kernel32$MENU_EVENT_RECORD failed. Use the option

    '--initialize-at-run-time=org.jline.nativ.Kernel32$MENU_EVENT_RECORD'

 to explicitly request initialization of this class at run time.
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.ensureOnTypeReachableTaskDone(AnalysisType.java:696)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.onReachable(AnalysisType.java:590)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AtomicUtils.atomicSetAndRun(AtomicUtils.java:49)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.lambda$registerAsReachable$8(AnalysisType.java:562)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:676)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:659)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:655)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.registerAsReachable(AnalysisType.java:562)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.registerAsAllocated(AnalysisType.java:504)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ReachabilityAnalysis.registerTypeAsAllocated(ReachabilityAnalysis.java:107)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jni.JNIAccessFeature.lambda$addClass$3(JNIAccessFeature.java:347)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNIReflectionDictionary.addClassIfAbsent(JNIReflectionDictionary.java:138)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jni.JNIAccessFeature.addClass(JNIAccessFeature.java:342)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jni.JNIAccessFeature.duringAnalysis(JNIAccessFeature.java:315)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:786)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)
        ... 9 more

```

My dependencies in pom.xml:

```xml
 <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline</artifactId>
            <version>${jline.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-native</artifactId>
            <version>${jline.version}</version>
        </dependency>
```

Anything I'm missing as configuration?

**Comment by gnodet** [comment]
The demo https://github.com/jline/jline3/blob/jline-parent-3.25.1/graal/pom.xml#L104-L108 seems to work, maybe you need to use the same command line parameters ?

Also I would advise to use the small jars instead of the bigger `jline` bundle btw.

Please reopen if needed.
