### ISSUE TITLE
 Error executing 'stty icrnl ixon echo icanon iexten' on OSX with homebrew coreutils installed

### ISSUE THREAD

**Issue by michelemostarda** [jline/jline3#97]
I've this error at first command submission with jline3 on OSX 10.12.13 with gnubin/stty (**coreutils installed by homebrew**  in response of some dependency).

```
$stty --version
stty (GNU coreutils) 8.26
```

The problem is bypassed if I prioritize the original stty in PATH

>  PATH="/bin:$PATH"

I found some hint here:

https://github.com/alexch/rerun/issues/62#issuecomment-141267649

Issue stack trace:

```
rdfcoder-github$ bin/rdfcoder
Initializing JRE data ...
 INFO [main] (JavaProfile.java:278) - Objects Table loaded.
JRE data loaded.
RDFCoder interactive console [version 0.5]
.~default> help 
Exception in thread "main" java.io.IOError: java.io.IOException: Error executing 'stty icrnl ixon echo icanon iexten': stty: 'standard input': unable to perform all requested operations
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:573)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:388)
	at com.asemantics.rdfcoder.AbstractCommandLine.readInput(AbstractCommandLine.java:1544)
	at com.asemantics.rdfcoder.AbstractCommandLine.mainCycle(AbstractCommandLine.java:1185)
	at com.asemantics.rdfcoder.AbstractCommandLine.main(AbstractCommandLine.java:307)
Caused by: java.io.IOException: Error executing 'stty icrnl ixon echo icanon iexten': stty: 'standard input': unable to perform all requested operations
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
	at org.jline.terminal.impl.ExecPty.setAttr(ExecPty.java:146)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:50)
	... 5 more
```

**Comment by michelemostarda** [comment]
<3
